### ISSUE TITLE
Pet Clinic Selenium/Cucumber tests are failing

### ISSUE THREAD

**Issue by deors** [Accenture/adop-cartridge-java#4]
I have created a brand new ADOP instance today, and this time the Selenium/Cucumber tests are failing. Visually, the Pet Clinic web interface looks a bit different, i.e. table with results of Find Owners is wider than before. Could it be that we are pushing Pet Clinic bits from a external source and that there has been a new commit to that repo which is causing our tests to fail?

**Comment by nickdgriffin** [comment]
That's exactly the problem, and have just run into the same thing testing the CLI implementation.

The cartridge pulls from the main Spring Petclinic repository and they've recently made a huge change which has broken the tests. I force pushed the commit before and the pipeline went through fine. We could fork their repository and use that so we stay stable.

**Comment by deors** [comment]
A fork will definitely be a good idea. Pet Clinic is not changed very often
but we need independence on its release cycle to ensure ADOP reference
pipeline is not broken. Moreover, to properly configure some stuff as
mutation tests or code coverage per test we would need to fine tune the
POM, so eventually we would need the fork anyway.

**Comment by nickdgriffin** [comment]
OK, I'll fork later today and set ours to use the commit before everything changed then update the cartridge to use that.

**Comment by nickdgriffin** [comment]
This should be resolved now by my PR.

**Comment by deors** [comment]
I confirm it is closed now.
