### ISSUE TITLE
Remote GET and POST to Jenkins build and REST API fails with 401 error

### ISSUE THREAD

**Issue by jaynathani-granube** [Accenture/adop-cartridge-java#41]
Hello

I am trying to trigger a remote build to the pipeline created after uploading the java cartridge. Whatever configurations I try, they have failed and have returned a 401 error. I am also trying to get information from the pipeline using the REST API json, even that is giving me the same error.

I tried "Anyone can do anything" under authorization in Manage Jenkins/Configure Global Security, even that gave me the same 401 authorized required error.

I even tried using API token but got the same error.

Please tell me what changes should I make so that I can trigger remote builds to the pipeline from anywhere. 

Thanks
Jay

**Comment by nickdgriffin** [comment]
Hi Jay,

Authentication occurs at the proxy so that is why you are getting a 401 - it always requires credentials when coming from the outside. 

Removing authentication means that there is no security at all so anyone anywhere could do things against that Jenkins instance if they had connectivity.

Cheers,
Nick

**Comment by jaynathani-granube** [comment]
Hi Nick,

I was not removing authentication, I was trying to see if the HTTP Get/Post request was working.

Can you please elaborate a little on how I can give credentials for the proxy in the Get/Post requests? I tried adding username and password in headers. I also tried adding username and tokenId in headers. Neither of them worked. 

Thanks
Jay

**Comment by nickdgriffin** [comment]
Hi Jay,

We do this in the the CLI, you can see an example here: https://github.com/Accenture/adop-docker-compose/blob/master/cmd/workspace#L81

Cheers,
Nick

**Comment by jaynathani-granube** [comment]
Hi Nick,

That is very helpful. I had actually figured that out yesterday after I added the comment to this issue. 

Thanks
Jay
