### ISSUE TITLE
Enhancement: Add performance testing with JMeter and Gatling to the reference pipeline

### ISSUE THREAD

**Issue by deors** [Accenture/adop-cartridge-java#9]
Add a new step for performance testing with JMeter and Gatling to the reference pipeline

**Comment by nickdgriffin** [comment]
This might be a short lived issue, @nhantd is already working on this at the moment.

**Comment by deors** [comment]
Cool! Looking forward to it.

**Comment by deors** [comment]
Thanks @nhantd and @nickdgriffin. Just provisioned an instance with the enhanced pipeline and it looks awesome. Closing the issue.
